### PR TITLE
[MF] Add Item button that opens dialog on List.jsx WIP

### LINKED ISSUE #46: Turn add item into dialog

### PR DESCRIPTION
**Pull request by krsnamara**
## Description

This code adds a button on the List page that opens a React portal modal component found here in the docs [Rendering modal dialog with portal](https://react.dev/reference/react-dom/createPortal#rendering-a-modal-dialog-with-a-portal). In this modal the user can add items from the list page without needing to navigate to the manage-list page. I used the React component to access some default styling and it's ease of use. I chose to not make the 'AddItem' a reusable component because I did not see a need for it some place else.

## Related Issue

Sub-Issue of #14
Closes #46 

## Acceptance Criteria

TBD

## Type of Changes

Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.

## Testing Steps / QA Criteria

Login, select list, click on big green button, the values at this point can only be added by pasting and the radios are not currently working. I need to look over the state of those values and how it is handled.

### CODE REVIEW

**Comment by krsnamara** [comment]
Closing this PR as we now are using the Dialog component to render the modal

**Comment by krsnamara** [comment]
##UPDATE TO THE ORIGINAL PR

## Description

This code adds a button on the List page that uses our Dialog component built from @mxmason's example. In this dialog the user can add items from the list page without needing to navigate to the manage-list page.

## Related Issue

Sub-Issue of #14
Closes #46 

## Type of Changes

Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.

## Updates

### Before

Screenshot 2024-03-25 at 11 52 42 AM

### After

Screenshot 2024-03-25 at 11 54 08 AM

Screenshot 2024-03-25 at 11 58 16 AM

Screenshot 2024-03-25 at 12 07 17 PM


## Testing Steps / QA Criteria

Login, select list, click on big green button, the values at this point can only be added by pasting and the radios are not currently working. I need to look over the state of those values and how it is handled.

**Comment by piecanoe** [comment]
Great job on this, Marty. I know this one was real a brain-swirler. It seems to be working correctly on my end.

Nit: after I add the first item and I click the green button to add another item, the "Item Name" field shows the previous item and previous radio selection. Is there a way to have this reset so the field is empty and the radio default is "Soon" again?

**Review by piecanoe — APPROVED** [review]

**Comment by krsnamara** [comment]
@piecanoe 
> Great job on this, Marty. I know this one was real a brain-swirler. It seems to be working correctly on my end.
> 
> Nit: after I add the first item and I click the green button to add another item, the "Item Name" field shows the previous item and previous radio selection. Is there a way to have this reset so the field is empty and the radio default is "Soon" again?

Added these changes in new commits. Values and UI updates. Also added similar update to shareList Dialog.

**Review by hsiangj — APPROVED** [review]
🙌 Great job @krsnamara!! Tricky one to implement, and everything works as expected.

**Comment by krsnamara** [comment]
Going to merge this for the demo

**Pull request merged**
