### PR TITLE
[JH] Restrict Route Access 

### LINKED ISSUE #51: Restrict Route Access
## Summary
Restrict route access to view list items and manage items when user is not signed in. User should be redirected to Home to sign in. 

## Acceptance criteria
- [x] Users who are not signed in won't be able to navigate to "List" and "Manage List" pages via navbar or directly through the URL.

## Notes
Sub-issue of https://github.com/the-collab-lab/tcl-69-smart-shopping-list/issues/14

### PR DESCRIPTION
**Pull request by hsiangj**
## Description

This code restricts route access to "List" and "Manage List" when user is not signed in. Using the `<Navigate>` component, user is redirected to "Home" or "/" route path to sign in. 

Note: The route path to "Home" currently renders information about user's lists. This may be changed to the landing page in a future issue.  

## Related Issue

Closes #51 
Sub-issue of #14 

## Acceptance Criteria

- [x] Users who are not signed in won't be able to navigate to "List" and "Manage List" pages via navbar or directly through the URL.

## Type of Changes

Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.

### Before
Successfully navigated to "Manage List" page without signing in.
Screen Shot 2024-03-21 at 2 17 33 PM

### After
Page redirected to "Home" when clicking on "Manage List."
Screen Shot 2024-03-21 at 2 20 35 PM

## Testing Steps / QA Criteria
1. Without signing in, try navigate to "List" page using the navbar or direct URL (/list). Page should redirect to "Home."
2. Repeat for "Manage List."

### CODE REVIEW

**Comment by hsiangj** [comment]
The original idea was to implement useContext to share current user info. However, there is already a current user object from the useAuth hook set up in App.jsx.

**Review by krsnamara — APPROVED** [review]
Curious why you chose not to useContext? 
I think the way you accomplished this was super clean and to the point. 
Great work!

**Review by piecanoe — APPROVED** [review]
Looks great! Works as it should.

**Review by amalyam — APPROVED** [review]
Nice, works as expected!

**Pull request merged**
